# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pictures.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QCheckBox,
    QComboBox, QDateEdit, QFrame, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QProgressBar, QPushButton, QScrollArea,
    QSizePolicy, QTabWidget, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_ImageViewer(object):
    def setupUi(self, ImageViewer):
        if not ImageViewer.objectName():
            ImageViewer.setObjectName(u"ImageViewer")
        ImageViewer.resize(1386, 871)
        self.tabWidget = QTabWidget(ImageViewer)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 20, 671, 761))
        font = QFont()
        font.setBold(False)
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.lineEdit = QLineEdit(self.tab)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 10, 541, 31))
        self.pushButton = QPushButton(self.tab)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(572, 10, 81, 31))
        self.pushButton_2 = QPushButton(self.tab)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(572, 50, 81, 31))
        self.pushButton_3 = QPushButton(self.tab)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(460, 90, 91, 31))
        self.pushButton_4 = QPushButton(self.tab)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(570, 90, 81, 31))
        self.comboBox = QComboBox(self.tab)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 90, 151, 31))
        self.comboBox.setInsertPolicy(QComboBox.InsertAlphabetically)
        self.comboBox_2 = QComboBox(self.tab)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(180, 90, 141, 31))
        self.lineEdit_2 = QLineEdit(self.tab)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(10, 50, 541, 31))
        self.listWidget = QListWidget(self.tab)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(10, 190, 641, 161))
        self.listWidget.setEditTriggers(QAbstractItemView.DoubleClicked|QAbstractItemView.EditKeyPressed|QAbstractItemView.SelectedClicked)
        self.listWidget_2 = QListWidget(self.tab)
        self.listWidget_2.setObjectName(u"listWidget_2")
        self.listWidget_2.setGeometry(QRect(10, 380, 641, 121))
        self.listWidget_3 = QListWidget(self.tab)
        self.listWidget_3.setObjectName(u"listWidget_3")
        self.listWidget_3.setGeometry(QRect(10, 660, 641, 91))
        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 170, 191, 16))
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 360, 641, 16))
        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 640, 491, 16))
        self.listWidget_4 = QListWidget(self.tab)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(10, 530, 641, 101))
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 510, 641, 16))
        self.pushButton_5 = QPushButton(self.tab)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(350, 90, 93, 28))
        self.pushButton_12 = QPushButton(self.tab)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(400, 632, 93, 28))
        self.pushButton_13 = QPushButton(self.tab)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(522, 632, 131, 28))
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 130, 111, 16))
        self.lineEdit_17 = QLineEdit(self.tab)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(120, 130, 531, 21))
        self.pushButton_10 = QPushButton(self.tab)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(480, 155, 171, 31))
        self.checkBox_7 = QCheckBox(self.tab)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(370, 160, 96, 19))
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, -31, 1381, 801))
        self.tabWidget.addTab(self.tab, "")
        self.groupBox_2.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.lineEdit_2.raise_()
        self.listWidget.raise_()
        self.listWidget_2.raise_()
        self.listWidget_3.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.listWidget_4.raise_()
        self.label_13.raise_()
        self.pushButton_5.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.label_8.raise_()
        self.lineEdit_17.raise_()
        self.pushButton_10.raise_()
        self.checkBox_7.raise_()
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_16 = QPushButton(self.tab_2)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(540, 710, 111, 21))
        self.lineEdit_13 = QLineEdit(self.tab_2)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(180, 100, 321, 21))
        self.lineEdit_13.setReadOnly(True)
        self.pushButton_17 = QPushButton(self.tab_2)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(360, 710, 161, 21))
        self.pushButton_18 = QPushButton(self.tab_2)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(530, 100, 121, 21))
        self.pushButton_20 = QPushButton(self.tab_2)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(530, 0, 121, 91))
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 190, 491, 16))
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 10, 64, 21))
        self.label_16.setFrameShape(QFrame.WinPanel)
        self.label_16.setFrameShadow(QFrame.Raised)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.dateEdit = QDateEdit(self.tab_2)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(130, 10, 101, 22))
        self.dateEdit.setCalendarPopup(True)
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(80, 10, 41, 21))
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(240, 10, 41, 21))
        self.label_19.setAlignment(Qt.AlignCenter)
        self.dateEdit_2 = QDateEdit(self.tab_2)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.dateEdit_2.setGeometry(QRect(280, 10, 101, 22))
        self.dateEdit_2.setDateTime(QDateTime(QDate(2004, 1, 31), QTime(0, 0, 0)))
        self.dateEdit_2.setCalendarPopup(True)
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 100, 61, 21))
        self.label_20.setFrameShape(QFrame.Panel)
        self.label_20.setFrameShadow(QFrame.Raised)
        self.label_20.setAlignment(Qt.AlignCenter)
        self.lineEdit_3 = QLineEdit(self.tab_2)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(80, 160, 231, 21))
        self.lineEdit_3.setReadOnly(True)
        self.checkBox = QCheckBox(self.tab_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QRect(120, 700, 21, 21))
        self.checkBox.setTristate(False)
        self.label_21 = QLabel(self.tab_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 160, 61, 21))
        self.label_21.setFrameShape(QFrame.Panel)
        self.label_21.setFrameShadow(QFrame.Raised)
        self.label_21.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(self.tab_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(320, 160, 61, 21))
        self.label_22.setFrameShape(QFrame.Panel)
        self.label_22.setFrameShadow(QFrame.Raised)
        self.label_22.setAlignment(Qt.AlignCenter)
        self.lineEdit_11 = QLineEdit(self.tab_2)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(390, 160, 271, 21))
        self.lineEdit_11.setReadOnly(True)
        self.tableWidget = QTableWidget(self.tab_2)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 210, 661, 431))
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.label_23 = QLabel(self.tab_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(80, 100, 81, 21))
        self.label_23.setFrameShape(QFrame.Panel)
        self.label_23.setFrameShadow(QFrame.Raised)
        self.label_23.setAlignment(Qt.AlignCenter)
        self.label_24 = QLabel(self.tab_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(80, 130, 81, 21))
        self.label_24.setFrameShape(QFrame.Panel)
        self.label_24.setFrameShadow(QFrame.Raised)
        self.label_24.setAlignment(Qt.AlignCenter)
        self.lineEdit_14 = QLineEdit(self.tab_2)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(180, 129, 321, 21))
        self.label_25 = QLabel(self.tab_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(510, 130, 41, 21))
        self.label_25.setFrameShape(QFrame.Panel)
        self.label_25.setFrameShadow(QFrame.Raised)
        self.label_25.setAlignment(Qt.AlignCenter)
        self.lineEdit_15 = QLineEdit(self.tab_2)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(560, 130, 91, 21))
        self.lineEdit_15.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_15.setReadOnly(True)
        self.label_26 = QLabel(self.tab_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 40, 64, 21))
        self.label_26.setFrameShape(QFrame.WinPanel)
        self.label_26.setFrameShadow(QFrame.Raised)
        self.label_26.setAlignment(Qt.AlignCenter)
        self.label_27 = QLabel(self.tab_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 70, 64, 21))
        self.label_27.setFrameShape(QFrame.WinPanel)
        self.label_27.setFrameShadow(QFrame.Raised)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.checkBox_3 = QCheckBox(self.tab_2)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(460, 40, 61, 20))
        self.checkBox_4 = QCheckBox(self.tab_2)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(460, 70, 61, 20))
        self.lineEdit_12 = QLineEdit(self.tab_2)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(90, 40, 361, 20))
        self.lineEdit_16 = QLineEdit(self.tab_2)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(90, 70, 361, 20))
        self.checkBox_5 = QCheckBox(self.tab_2)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(410, 10, 81, 16))
        self.pushButton_14 = QPushButton(self.tab_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(20, 710, 91, 28))
        self.pushButton_15 = QPushButton(self.tab_2)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(150, 680, 93, 28))
        self.checkBox_8 = QCheckBox(self.tab_2)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setEnabled(False)
        self.checkBox_8.setGeometry(QRect(250, 700, 21, 21))
        self.checkBox_8.setTristate(False)
        self.pushButton_8 = QPushButton(self.tab_2)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(20, 680, 91, 31))
        self.pushButton_19 = QPushButton(self.tab_2)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(150, 710, 93, 28))
        self.pushButton_21 = QPushButton(self.tab_2)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(280, 680, 75, 31))
        self.checkBox_9 = QCheckBox(self.tab_2)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setEnabled(False)
        self.checkBox_9.setGeometry(QRect(280, 720, 81, 16))
        self.comboBox_3 = QComboBox(self.tab_2)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(140, 650, 94, 22))
        self.comboBox_3.setInsertPolicy(QComboBox.InsertAtBottom)
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 650, 101, 21))
        self.label_28 = QLabel(self.tab_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(460, 650, 81, 16))
        self.comboBox_4 = QComboBox(self.tab_2)
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(550, 650, 94, 22))
        self.label_29 = QLabel(self.tab_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(240, 650, 101, 16))
        self.comboBox_5 = QComboBox(self.tab_2)
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(350, 650, 94, 22))
        self.pushButton_22 = QPushButton(self.tab_2)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(370, 680, 111, 23))
        self.tabWidget.addTab(self.tab_2, "")
        self.frame = QFrame(ImageViewer)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(670, 550, 691, 231))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setLineWidth(3)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 200, 501, 21))
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 51, 71, 21))
        self.lineEdit_4 = QLineEdit(self.frame)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(110, 50, 111, 21))
        self.lineEdit_4.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 80, 81, 21))
        self.lineEdit_5 = QLineEdit(self.frame)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(110, 80, 111, 21))
        self.lineEdit_5.setAlignment(Qt.AlignCenter)
        self.lineEdit_6 = QLineEdit(self.frame)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(340, 80, 111, 21))
        self.lineEdit_6.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(250, 80, 81, 21))
        self.lineEdit_8 = QLineEdit(self.frame)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(110, 140, 113, 21))
        self.lineEdit_8.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 110, 81, 16))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(250, 110, 81, 16))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 140, 81, 16))
        self.lineEdit_7 = QLineEdit(self.frame)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(110, 110, 113, 21))
        self.lineEdit_7.setAlignment(Qt.AlignCenter)
        self.lineEdit_9 = QLineEdit(self.frame)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(340, 110, 113, 21))
        self.lineEdit_9.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(23, 10, 611, 31))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_9.setFont(font1)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.progressBar = QProgressBar(self.frame)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 170, 651, 23))
        self.progressBar.setValue(0)
        self.label_14 = QLabel(self.frame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(470, 110, 81, 16))
        self.lineEdit_10 = QLineEdit(self.frame)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(560, 110, 113, 21))
        self.lineEdit_10.setAlignment(Qt.AlignCenter)
        self.pushButton_6 = QPushButton(ImageViewer)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(680, 510, 93, 28))
        self.pushButton_7 = QPushButton(ImageViewer)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(790, 510, 93, 28))
        self.groupBox = QGroupBox(ImageViewer)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(670, 10, 691, 531))
        self.scrollArea = QScrollArea(self.groupBox)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(15, 16, 671, 481))
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(Qt.AlignCenter)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 669, 479))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.checkBox_2 = QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(220, 500, 121, 21))
        self.pushButton_9 = QPushButton(self.groupBox)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(540, 500, 141, 28))
        self.pushButton_11 = QPushButton(self.groupBox)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(340, 500, 93, 28))
        self.checkBox_6 = QCheckBox(self.groupBox)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(460, 500, 71, 19))
        self.groupBox.raise_()
        self.tabWidget.raise_()
        self.frame.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()

        self.retranslateUi(ImageViewer)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(ImageViewer)
    # setupUi

    def retranslateUi(self, ImageViewer):
        ImageViewer.setWindowTitle(QCoreApplication.translate("ImageViewer", u"Graphic File Control and Image Viewer", None))
        self.pushButton.setText(QCoreApplication.translate("ImageViewer", u"\uc6d0\ubcf8 \ud3f4\ub354", None))
        self.pushButton_2.setText(QCoreApplication.translate("ImageViewer", u"\ubaa9\uc801 \ud3f4\ub354", None))
        self.pushButton_3.setText(QCoreApplication.translate("ImageViewer", u"\ubcf5    \uc0ac", None))
        self.pushButton_4.setText(QCoreApplication.translate("ImageViewer", u"\uc774   \ub3d9", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("ImageViewer", u"\ub144/\uc6d4/\uc77c\ubcc4\ub85c \uc815\ub9ac", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("ImageViewer", u"\ub144/\uc6d4\ubcc4\ub85c \uc815\ub9ac", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("ImageViewer", u"\ub144\ubcc4\ub85c \uc815\ub9ac", None))

        self.comboBox_2.setItemText(0, QCoreApplication.translate("ImageViewer", u"2023\ub14402\uc6d408\uc77c", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("ImageViewer", u"2023-02-08", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("ImageViewer", u"2023_02_08", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("ImageViewer", u"20230208", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("ImageViewer", u"2023.02.08", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("ImageViewer", u"2023 02 08", None))

        self.label_10.setText(QCoreApplication.translate("ImageViewer", u"\ucd1d \uc791\uc5c5 \ud30c\uc77c \ubaa9\ub85d", None))
        self.label_11.setText(QCoreApplication.translate("ImageViewer", u"\uc0ac\uc9c4, \ubcf5\uc0ac \ub610\ub294 \uc774\ub3d9 \ud30c\uc77c \ubaa9\ub85d", None))
        self.label_12.setText(QCoreApplication.translate("ImageViewer", u"\uc0ac\uc9c4 \ud30c\uc77c \uc774\uc678\uc758 \ud30c\uc77c \ubaa9\ub85d", None))
        self.label_13.setText(QCoreApplication.translate("ImageViewer", u"\uae30\uc874 \uc874\uc7ac \ud30c\uc77c\ub85c \ubcf5\uc0ac\uac00 \uc548\ub418\uac70\ub098 \uc0ad\uc81c(\uc774\ub3d9 \uae30\ub2a5\uc2dc)\ub41c \uc0ac\uc9c4 \ud30c\uc77c \ubaa9\ub85d", None))
        self.pushButton_5.setText(QCoreApplication.translate("ImageViewer", u"File List", None))
        self.pushButton_12.setText(QCoreApplication.translate("ImageViewer", u"\uc120\ud0dd\ud30c\uc77c \uc0ad\uc81c", None))
        self.pushButton_13.setText(QCoreApplication.translate("ImageViewer", u"\uae30\ud0c0\ud30c\uc77c \uc804\uccb4 \uc0ad\uc81c", None))
        self.label_8.setText(QCoreApplication.translate("ImageViewer", u"Slide File Name", None))
        self.pushButton_10.setText(QCoreApplication.translate("ImageViewer", u"ListWidget Slide Show", None))
        self.checkBox_7.setText(QCoreApplication.translate("ImageViewer", u"Show Stop", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("ImageViewer", u"GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("ImageViewer", u"\ub0a0\uc9dc\ubcc4 \uc815\ub9ac", None))
        self.pushButton_16.setText(QCoreApplication.translate("ImageViewer", u"\uc120\ud0dd\ud30c\uc77c \uc0ad\uc81c", None))
        self.pushButton_17.setText(QCoreApplication.translate("ImageViewer", u"\ub9ac\uc2a4\ud2b8\ud30c\uc77c \uc804\uccb4 \uc0ad\uc81c", None))
        self.pushButton_18.setText(QCoreApplication.translate("ImageViewer", u"Folder Rename", None))
        self.pushButton_20.setText(QCoreApplication.translate("ImageViewer", u"Data \uac80\uc0c9", None))
        self.label_18.setText(QCoreApplication.translate("ImageViewer", u"\ucd1d \uac80\uc0c9 \ud30c\uc77c \ubaa9\ub85d", None))
        self.label_16.setText(QCoreApplication.translate("ImageViewer", u"\uac80\uc0c9\uae30\uac04", None))
        self.label_17.setText(QCoreApplication.translate("ImageViewer", u"From", None))
        self.label_19.setText(QCoreApplication.translate("ImageViewer", u"To", None))
        self.label_20.setText(QCoreApplication.translate("ImageViewer", u"Remark", None))
        self.checkBox.setText("")
        self.label_21.setText(QCoreApplication.translate("ImageViewer", u"File Name", None))
        self.label_22.setText(QCoreApplication.translate("ImageViewer", u"Directory", None))
        self.label_23.setText(QCoreApplication.translate("ImageViewer", u"Change From", None))
        self.label_24.setText(QCoreApplication.translate("ImageViewer", u"Change To", None))
        self.label_25.setText(QCoreApplication.translate("ImageViewer", u"Row", None))
        self.label_26.setText(QCoreApplication.translate("ImageViewer", u"\uac80\uc0c9\ud30c\uc77c", None))
        self.label_27.setText(QCoreApplication.translate("ImageViewer", u"\ud589\uc0ac\uc885\ub958", None))
        self.checkBox_3.setText(QCoreApplication.translate("ImageViewer", u"like", None))
        self.checkBox_4.setText(QCoreApplication.translate("ImageViewer", u"like", None))
        self.checkBox_5.setText(QCoreApplication.translate("ImageViewer", u"\uc804\uccb4\uae30\uac04", None))
        self.pushButton_14.setText(QCoreApplication.translate("ImageViewer", u"Stop", None))
        self.pushButton_15.setText(QCoreApplication.translate("ImageViewer", u"Pause", None))
        self.checkBox_8.setText("")
        self.pushButton_8.setText(QCoreApplication.translate("ImageViewer", u"Start", None))
        self.pushButton_19.setText(QCoreApplication.translate("ImageViewer", u"Resume", None))
        self.pushButton_21.setText(QCoreApplication.translate("ImageViewer", u"cv2 Show", None))
        self.checkBox_9.setText(QCoreApplication.translate("ImageViewer", u"cV2 Show ", None))
        self.label_15.setText(QCoreApplication.translate("ImageViewer", u"Wait Time(ms)", None))
        self.label_28.setText(QCoreApplication.translate("ImageViewer", u"Play Speed", None))
        self.label_29.setText(QCoreApplication.translate("ImageViewer", u"Play Frame(%)", None))
        self.pushButton_22.setText(QCoreApplication.translate("ImageViewer", u"Reverse Show", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("ImageViewer", u"\ud30c\uc77c\uad00\ub9ac \ubc0f \uc0ac\uc9c4 \ubcf4\uae30", None))
        self.label.setText(QCoreApplication.translate("ImageViewer", u"TextLabel", None))
        self.label_2.setText(QCoreApplication.translate("ImageViewer", u"Total Files", None))
        self.label_3.setText(QCoreApplication.translate("ImageViewer", u"Graphic Files", None))
        self.label_4.setText(QCoreApplication.translate("ImageViewer", u"Other Files", None))
        self.label_5.setText(QCoreApplication.translate("ImageViewer", u"Copyed Files", None))
        self.label_7.setText(QCoreApplication.translate("ImageViewer", u"Existed Files", None))
        self.label_6.setText(QCoreApplication.translate("ImageViewer", u"Moved Files", None))
        self.lineEdit_9.setText("")
        self.label_9.setText(QCoreApplication.translate("ImageViewer", u"\uc18c\uc7a5 \uc0ac\uc9c4\uc758 \uc77c\uc790\ubcc4 \uc0ac\uc9c4 \uc815\ub9ac \ubc0f \ubdf0\uc5b4 \ud504\ub85c\uadf8\ub7a8", None))
        self.label_14.setText(QCoreApplication.translate("ImageViewer", u"Identical Files", None))
        self.lineEdit_10.setText("")
        self.pushButton_6.setText(QCoreApplication.translate("ImageViewer", u"\ud655  \ub300", None))
        self.pushButton_7.setText(QCoreApplication.translate("ImageViewer", u"\ucd95  \uc18c", None))
        self.groupBox.setTitle(QCoreApplication.translate("ImageViewer", u"GroupBox", None))
        self.checkBox_2.setText(QCoreApplication.translate("ImageViewer", u"Fit to Window", None))
        self.pushButton_9.setText(QCoreApplication.translate("ImageViewer", u"Fit to Scaled Size", None))
        self.pushButton_11.setText(QCoreApplication.translate("ImageViewer", u"Normal", None))
        self.checkBox_6.setText(QCoreApplication.translate("ImageViewer", u"Scaled", None))
    # retranslateUi

