# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pictures_control.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QToolBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(904, 534)
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 10, 651, 71))
        font1 = QFont()
        font1.setFamilies([u"HY\ud5e4\ub4dc\ub77c\uc778M"])
        font1.setPointSize(16)
        self.label.setFont(font1)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QFrame.Panel)
        self.label.setFrameShadow(QFrame.Plain)
        self.label.setLineWidth(6)
        self.label.setMidLineWidth(0)
        self.label.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 92, 841, 71))
        font2 = QFont()
        font2.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font2.setPointSize(10)
        font2.setBold(False)
        self.groupBox.setFont(font2)
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 30, 691, 31))
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(730, 29, 91, 31))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(30, 172, 841, 71))
        self.groupBox_2.setFont(font2)
        self.lineEdit_2 = QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(10, 30, 691, 31))
        self.pushButton_2 = QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(730, 29, 91, 31))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(30, 270, 841, 131))
        self.groupBox_5.setFont(font2)
        self.lineEdit_5 = QLineEdit(self.groupBox_5)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(89, 30, 181, 31))
        self.label_2 = QLabel(self.groupBox_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(12, 33, 71, 21))
        self.label_3 = QLabel(self.groupBox_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(303, 33, 71, 21))
        self.lineEdit_6 = QLineEdit(self.groupBox_5)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(380, 30, 181, 31))
        self.label_4 = QLabel(self.groupBox_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(573, 33, 71, 21))
        self.lineEdit_7 = QLineEdit(self.groupBox_5)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(650, 30, 181, 31))
        self.label_8 = QLabel(self.groupBox_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(428, 80, 90, 31))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        self.label_8.setFont(font3)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.lineEdit_11 = QLineEdit(self.groupBox_5)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(550, 80, 181, 31))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 430, 311, 31))
        font4 = QFont()
        font4.setPointSize(10)
        self.label_5.setFont(font4)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(547, 430, 151, 41))
        font5 = QFont()
        font5.setBold(True)
        self.pushButton_5.setFont(font5)
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(720, 430, 151, 41))
        self.pushButton_6.setFont(font5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 904, 26))
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uc784\ud6c8\ud0dd's \uc0ac\uc9c4 \ubd84\ub958 \uc2dc\uc2a4\ud15c \ud504\ub85c\uadf8\ub7a8", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8 \uc0ac\uc9c4 \ud30c\uc77c \ub514\ub809\ud1a0\ub9ac \uc124\uc815", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8 \uc0ac\uc9c4", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\ubd84\ub958 \uc0ac\uc9c4 \uc800\uc7a5 \ub514\ub809\ud1a0\ub9ac \uc124\uc815", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\ubd84\ub958 \uc0ac\uc9c4", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\uc0ac\uc9c4 \uc790\ub8cc \ud604\ud669", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8 \uc0ac\uc9c4", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\ubd84\ub958 \uc0ac\uc9c4", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\uc911\ubcf5 \uc0ac\uc9c4", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\ucd1d \ud569 \uacc4", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\ud504\ub85c\uadf8\ub7a8 \uc791\uc131 : \uc784\ud6c8\ud0dd Rev 0, 2023.00.00 Issued", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\ubd84\ub958 \uc2dc\uc791", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\uc885     \ub8cc", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

