# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'elec_separate_mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QToolBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1008, 766)
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(170, 10, 651, 71))
        font1 = QFont()
        font1.setFamilies([u"HY\ud5e4\ub4dc\ub77c\uc778M"])
        font1.setPointSize(16)
        self.label.setFont(font1)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QFrame.Panel)
        self.label.setFrameShadow(QFrame.Plain)
        self.label.setLineWidth(6)
        self.label.setMidLineWidth(0)
        self.label.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 92, 961, 71))
        font2 = QFont()
        font2.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font2.setPointSize(10)
        font2.setBold(False)
        self.groupBox.setFont(font2)
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 30, 781, 31))
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(830, 29, 91, 31))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(30, 172, 961, 71))
        self.groupBox_2.setFont(font2)
        self.lineEdit_2 = QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(10, 30, 781, 31))
        self.pushButton_2 = QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(830, 29, 91, 31))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(30, 332, 961, 71))
        self.groupBox_4.setFont(font2)
        self.lineEdit_3 = QLineEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(10, 30, 781, 31))
        self.pushButton_4 = QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(830, 29, 91, 31))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(30, 415, 961, 71))
        self.groupBox_3.setFont(font2)
        self.lineEdit_4 = QLineEdit(self.groupBox_3)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(10, 30, 781, 31))
        self.pushButton_3 = QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(830, 29, 91, 31))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(30, 490, 961, 171))
        self.groupBox_5.setFont(font2)
        self.lineEdit_5 = QLineEdit(self.groupBox_5)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(140, 30, 181, 31))
        self.label_2 = QLabel(self.groupBox_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(12, 33, 121, 21))
        self.label_3 = QLabel(self.groupBox_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(340, 33, 71, 21))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.lineEdit_6 = QLineEdit(self.groupBox_5)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(440, 30, 181, 31))
        self.label_4 = QLabel(self.groupBox_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(670, 30, 71, 21))
        self.lineEdit_7 = QLineEdit(self.groupBox_5)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(770, 30, 181, 31))
        self.label_7 = QLabel(self.groupBox_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 80, 111, 20))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        self.label_7.setFont(font3)
        self.label_8 = QLabel(self.groupBox_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(449, 120, 311, 31))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        self.label_8.setFont(font4)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.groupBox_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(640, 80, 111, 21))
        self.label_9.setFont(font3)
        self.lineEdit_10 = QLineEdit(self.groupBox_5)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(770, 80, 181, 31))
        self.lineEdit_11 = QLineEdit(self.groupBox_5)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(770, 120, 181, 31))
        self.label_10 = QLabel(self.groupBox_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(340, 80, 91, 31))
        self.label_10.setFont(font3)
        self.lineEdit_12 = QLineEdit(self.groupBox_5)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(440, 80, 181, 31))
        self.lineEdit_13 = QLineEdit(self.groupBox_5)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(140, 80, 181, 31))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 670, 311, 31))
        font5 = QFont()
        font5.setPointSize(10)
        self.label_5.setFont(font5)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(610, 670, 151, 41))
        font6 = QFont()
        font6.setBold(True)
        self.pushButton_5.setFont(font6)
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(820, 670, 151, 41))
        self.pushButton_6.setFont(font6)
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(400, 670, 151, 41))
        self.pushButton_7.setFont(font6)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(30, 250, 961, 71))
        self.groupBox_6.setFont(font2)
        self.lineEdit_15 = QLineEdit(self.groupBox_6)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(10, 30, 781, 31))
        self.pushButton_8 = QPushButton(self.groupBox_6)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(830, 29, 91, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1008, 21))
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uac15\ub0a8\ub370\uc2dc\uc559\ud30c\ud06c \uc544\ud30c\ud2b8 \uad00\ub9ac\uc0ac\ubb34\uc18c \uc804\uae30\uac10\uba74 \uc694\uae08 \uad00\ub9ac \ud504\ub85c\uadf8\ub7a8", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\ud55c\uc804 \ubcf5\uc9c0 \ud560\uc778 \ubc0f \ud544\uc218\uc0ac\uc6a9\uacf5\uc81c \uac10\uba74\uc790\ub8cc \ud30c\uc77c \uc120\ud0dd", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\ubcf5\uc9c0\ud560\uc778", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\ud55c\uc804 \ubcf5\uc9c0 \ud560\uc778 \uc885\ub958 \ubc0f \uac10\uba74\uc694\uae08 \uc790\ub8cc \ud30c\uc77c \uc120\ud0dd", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\ud560\uc778\uc885\ub958", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"XPERP Upload\uc6a9 Template \ud30c\uc77c \uc120\ud0dd", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Template", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"XPERP \ud560\uc778\uc790\ub8cc \uc5c5\ub85c\ub4dc\ud30c\uc77c \uc800\uc7a5\uacbd\ub85c", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\uacbd\ub85c", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\uacf5\uc81c \uc885\ub958\ubcc4 \ucd1d \uacf5\uc81c\uc694\uae08 \ud569\uacc4\uc561 \ud604\ud669\ud45c", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\ud544\uc218\uc0ac\uc6a9/\ubcf5\uc9c0\ucd94\uac00", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\uac00\uc871 \ud560\uc778", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\ubcf5\uc9c0  \ud560\uc778", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\uc5d0\ub108\uc9c0\uce90\uc2dc\ubc31", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\ucd1d \ud569 \uacc4 (\uac00\uc871 + \ubcf5\uc9c0 + \uc694\uae08\ub3d9\uacb0)", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\uac00\uc871 + \ubcf5\uc9c0 \uacc4", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\uc694\uae08\ub3d9\uacb0\ud560\uc778", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\ud504\ub85c\uadf8\ub7a8 \uc791\uc131 : \uc784\ud6c8\ud0dd Rev 2, 2024.02.23 Revised", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\uacc4\uc0b0 \uc2dc\uc791", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\uc885     \ub8cc", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\ud55c\uc804 \ud30c\uc77c \uac80\uc99d", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\uc804\uae30\uc694\uae08 \uac10\uba74\uc6a9 \ucf54\ub4dc \uc870\uacac\ud45c \ud30c\uc77c", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Code Table", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

